### PR TITLE
feat: add shitcoin

### PR DESCRIPTION
**Pull request by bfu4**
yea nano support

### CODE REVIEW

**Comment by bfu4** [comment]
oh also merge this to master, thx

**Comment by looskie** [comment]
Yeah

**Comment by driaug** [comment]
Closing this since since API does not support conversion both ways

**Comment by Looskie** [comment]
what

**Comment by alii** [comment]
what

**Comment by Hexiro** [comment]
what

**Comment by driaug** [comment]
Hi guys, I appreciate the comments and support but I would appreciate it if you could keep it professional. This is a serious project after all!

**Pull request closed without merging**
